---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
  labels:
    app: deployment-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-db
  template:
    metadata:
      labels:
        app: deployment-db
    spec:
      containers:
      - name: deployment-db
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ecompassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-load
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: db-load
        configMap:
          name: db-load-script

