---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
  labels:
    app: deployment-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-web
  template:
    metadata:
      labels:
        app: deployment-web
    spec:
      containers:
      - name: deployment-web
        image: acrk8s01.azurecr.io/web:v0.0.1
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mariadb-service
        - name: DB_USER
          value: ecomuser
        - name: DB_PASSWORD
          value: ecompassword
        - name: DB_NAME
          value: ecomdb
      imagePullSecrets:
      - name: acr-credentials
