---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
  labels:
    app: deployment-web
spec:
  replicas: 6
  selector:
    matchLabels:
      app: deployment-web
  template:
    metadata:
      labels:
        app: deployment-web
    spec:
      containers:
      - name: deployment-web
        image: acrk8s01.azurecr.io/web:v0.0.1
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: ecomuser
        - name: DB_PASSWORD
          value: ecompassword
        - name: DB_NAME
          value: ecomdb
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE
      volumeMounts:
      - name: theme-volume
        mountPath: /var/www/html/
      imagePullSecrets:
      - name: acr-credentials
    volumes:
    - name: theme-volume
      configMap:
        name: feature-toggle-config

